<?xml version="1.0" encoding="utf-8"?>
<!--  -*- Mode: xmldoc -*-  -->
<!DOCTYPE book [
<!ELEMENT book (chapter*)>
<!ELEMENT chapter (title,type,arguments?,package?,description,seealso*,link*,section,file?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT arguments (#PCDATA)>
<!ELEMENT package (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT seealso (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT section (#PCDATA)>
<!ELEMENT file (#PCDATA)>
]>
<!--
book
  ? chapter
      ? title
      ? type           Function, Special Form, Macro
      ?                Misc, Tips, Variable, BufferLocal
      ?                Keyword, Accessor
      ? arguments      Variable?Tips???
      ? package        Tips???
      ? description
      ? seealso        0?n?
      ? link           0?n?
      ? section        ???? ????? ????
      ?                ????? ?? ??? ????
      ?                ?? ?? ??? ?????
      ?                ??? ???? ?? ????
      ?                ?? ??? ????????
      ?                ??? ????? ????
      ?                ?????? ????? ???
      ?                ?????? ????? ????
      ?                ??????? ????? ?????
      ?                ???? ???? ?????
      ?                ???? ???? ???
      ? file            0 or 1
-->
<!--
<!ELEMENT (a, b)>     ?????
<!ELEMENT (a|b|c)>    ????????
<!ELEMENT x (a?)>     0???1??
<!ELEMENT x (a+)>     1?????
<!ELEMENT x (a*)>     0?????
-->
<book>
<% for chapter in book %>

<chapter>
<title><%=h chapter.title %></title>
<type><%=h chapter.type %></type>
<% if chapter.arguments %>
<arguments><%=h chapter.arguments %></arguments>
<% end %>
<% if chapter.package %>
<package><%=h chapter.package %></package>
<% end %>
<description>
<%=h chapter.description %>

</description>
<% for e in chapter.seealso %>
<seealso><%=h e %></seealso>
<% end %>
<section><%=h chapter.section %></section>
<file><%=h chapter.file %></file>
</chapter>
<% end %>
</book>
